import { accountPic } from "../../../../assets";
export const data = [
    {
      id: 1,
      education__level: "Primary",
      name: "Anny Whisley",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    },
    {
      id: 2,
      education__level: "Secondary",
      name: "Jackson White",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    },
    {
      id: 3,
      education__level: "Nursery",
      name: "Ashley Murphy",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    },
    {
      id: 4,
      education__level: "Primary",
      name: "Leonidas Williams",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    },
    {
      id: 5,
      education__level: "Nursary",
      name: "John Williams",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    },
    {
      id: 6,
      education__level: "Primary",
      name: "Alvarez Ruben",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    },
    {
      id: 7,
      education__level: "Secondary",
      name: "Diogo Jotta",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    },
    {
      id: 8,
      education__level: "Nursery",
      name: "Williams DuBois",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    },
    {
      id: 9,
      education__level: "Secondary",
      name: "Chwinjange Dupoko",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    },
    {
      id: 10,
      education__level: "Nursery",
      name: "John Doe",
      photo: accountPic,
      phone__number: "+243992028232",
      address_email: "annew@gmail.com",
      social__item: ['facebook__link', 'twitter__link'],
      course__item: ['Education civique', 'Informatique', 'chant'],
      class__item: ['4ieme', '5ieme', '3ieme'],
      preferences: 'J\'adore le Sport et faire du Sky',
    }
  ];